# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='density',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='density_kg_per_lt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Density (kg/lt)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='density_kg_per_pcs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Density (kg/pcs)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='density_pcs_per_lt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Density (pcs/lt)'),
        ),
    ]
