# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_auto_20170516_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='density_kg_per_pcs',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='density_pcs_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Density (pcs/kg)'),
        ),
    ]
