# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0005_auto_20170518_1826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name']},
        ),
    ]
