# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('recipe_ingredient_measurements', '0001_initial'),
        ('single_measurements', '0001_initial'),
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('primary_quantity', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Quantity')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('primary_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_unit', to='recipe_ingredient_measurements.RecipeIngredientMeasurements', verbose_name='Unit')),
                ('tags', models.ManyToManyField(blank=True, help_text='CTRL + Click for selecting more than one tag', related_name='recipes_recipe_tag', to='tags.Tag')),
            ],
            options={
                'ordering': ['-updated', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RecipePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='If left blank will be same as Ingredient name', max_length=200)),
                ('recipeposition_slug', models.SlugField(unique=True)),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Total Quantity')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(help_text='MUnit (Measurement Unit used while purchasing)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingredient_recipeposition', to='ingredients.Ingredient', verbose_name='ingredient (MUnit) - Rate/MUnit')),
                ('munit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipeposition_unit', to='single_measurements.SingleMeasurements', verbose_name='Measurement Unit')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_positions', to='recipes.Recipe')),
            ],
            options={
                'ordering': ['-updated', '-timestamp'],
            },
        ),
    ]
