# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20170516_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='mass_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pieces_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='primary_unit',
            field=models.CharField(choices=[('kg', 'Mass'), ('ltr', 'Volume'), ('pcs', 'Pieces')], default='ltr', max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='volume_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='recipeposition',
            name='mass_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='recipeposition',
            name='pieces_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='recipeposition',
            name='volume_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True),
        ),
    ]
