# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 18:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20170516_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='mass_quantity',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pieces_quantity',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='volume_quantity',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipeposition',
            name='mass_quantity',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipeposition',
            name='pieces_quantity',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipeposition',
            name='volume_quantity',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
