# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20170518_1826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['name', '-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='recipeposition',
            options={'ordering': ['updated', 'timestamp']},
        ),
    ]
