# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 17:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20170525_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='mass_quantity',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(1e-05)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pieces_quantity',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(1e-05)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='volume_quantity',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(1e-05)]),
        ),
    ]
