# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_recipe_overall_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='overall_updated',
        ),
    ]
