# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MenuIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menuingredient_ingredient', to='ingredients.Ingredient')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuingredient_menu', to='menu.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='MenuPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persons', models.PositiveSmallIntegerField(help_text='No of people for which the recipe will be made in this event', verbose_name='No of People')),
                ('person_Munit', models.CharField(choices=[('kg', 'Kilogram'), ('ltr', 'Liter'), ('pcs', 'Pieces')], default='kg', max_length=10)),
                ('quantity_per_person', models.DecimalField(decimal_places=5, help_text='Unit: Primary Unit used for the recipe', max_digits=19, verbose_name='Consumption per Person')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_positions', to='menu.Menu')),
                ('menurecipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menurecipe_positions', to='recipes.Recipe', verbose_name='Menu Recipe')),
            ],
            options={
                'ordering': ['-updated', '-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='menuingredients',
            name='menuposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuingredient_menuposition', to='menu.MenuPosition'),
        ),
        migrations.AddField(
            model_name='menuingredients',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuingredient_recipe', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='menuingredients',
            name='recipeposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuingredient_recipeposition', to='recipes.RecipePosition'),
        ),
    ]
