# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuposition',
            name='person_Munit',
        ),
        migrations.RemoveField(
            model_name='menuposition',
            name='quantity_per_person',
        ),
        migrations.AddField(
            model_name='menuposition',
            name='consumption_grams',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, help_text='Consumption per Person In Milliters', max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='menuposition',
            name='consumption_milli_liters',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, help_text='Consumption per Person In Milliters', max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='menuposition',
            name='consumption_pieces',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, help_text='Consumption per Person In Milliters', max_digits=19, null=True),
        ),
    ]
