# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20170517_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuposition',
            name='name',
            field=models.CharField(blank=True, help_text='If left blank will be same as Recipe name Eg: Ekadasi alu fry', max_length=200),
        ),
        migrations.AddField(
            model_name='menuposition',
            name='recipe_notes',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
