# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 11:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20170517_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuingredients',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='menuingredients',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='menuingredients',
            name='menuposition',
        ),
        migrations.RemoveField(
            model_name='menuingredients',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='menuingredients',
            name='recipeposition',
        ),
        migrations.AlterField(
            model_name='menuposition',
            name='consumption_grams',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, help_text='Consumption per Person In Milliters', max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='menuposition',
            name='consumption_milli_liters',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, help_text='Consumption per Person In Milliters', max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='menuposition',
            name='consumption_pieces',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, help_text='Consumption per Person In Milliters', max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.DeleteModel(
            name='MenuIngredients',
        ),
    ]
