# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 18:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20170518_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuposition',
            name='consumption_grams',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, help_text='Consumption per Person In Grams', max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='menuposition',
            name='consumption_pieces',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, help_text='Consumption per Person In Pieces', max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
