# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_menuposition_sequence_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuposition',
            options={'ordering': ['sequence_number']},
        ),
        migrations.AddField(
            model_name='menuposition',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
