# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 10:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_auto_20170524_1740'),
        ('menu', '0009_auto_20170528_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCustom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=19, validators=[django.core.validators.MinValueValidator(0)])),
                ('density_kg_per_lt', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Density (kg/lt)')),
                ('density_pcs_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Density (pcs/kg)')),
                ('density_pcs_per_lt', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Density (pcs/lt)')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredient_positions_customingredients', to='ingredients.Ingredient')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_positions_customingredients', to='menu.Menu')),
            ],
        ),
    ]
